### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by highhopes1** [Cale-Torino/FreeTAKServer_Manager#2]
Good evening, when I go to first log into the server using username: admin and password: password, I get an error saying 'Error 500 Internal Server Error'. I have a clean install of Python Version 3.8.9 as per the video and instructions. 

Any help would be greatly appreciated. 

![Uploading Screenshot 2021-09-25 at 21.31.23.png…]()

**Comment by Cale-Torino** [comment]
@highhopes1 Is the error in the browser or the cmd console? I can't see the screenshot for some reason so can't help you much.

**Comment by highhopes1** [comment]
The issue is within the browser after the server starts and the login screen appears.

**Comment by Cale-Torino** [comment]
@highhopes1 You will have to look at the console errors and try to debug. There is most likely an error with your `MainConfig.py`, `config.py` or `FTSConfig.yaml` if you are using the `.yaml` file.

Also when running for the first time the `FreeTAKServer.controllers.service` will ask if you want to use the `.yaml` file. Type in **No** otherwise you will need to configure `FTSConfig.yaml` which I have not setup the app to do automatically.
![Yamlnotused](https://user-images.githubusercontent.com/52330180/134803653-ed5f498f-4d1b-48d2-8a46-5a8f7cef66ed.jpg)

**Comment by highhopes1** [comment]
Amazing  that worked thank you so much.
